      # uri: mongodb+srv://admin:admin123@test.guzqdnv.mongodb.net/test
      # uri: mongodb+srv://admin:adim@test.guzqdnv.mongodb.net/?retryWrites=true&w=majority&appName=test
      # uri: mongodb+srv://kd1k:kd1k@cluster0.ipdmmye.mongodb.net/kd1k_development?retryWrites=true&w=majority
      # uri: mongodb://atlas-sql-64bae5ba29727b23acb050cc-gpttc.a.query.mongodb.net/test?ssl=true&authSource=admin
      # uri: mongodb+srv://kd1k:kd1k@Cluster0.ipdmmye.mongodb.net/kd1k_development
      # development:
      #  clients:
      #    default:
      #      uri: <%= ENV['MONGODB_URI'] %>
      #      options:
      #        server_selection_timeout: 5
      #        auto_source: Cluster0
      #        user: <%= ENV['USER'] %>
      #        password: <%= ENV['PASSWORD'] %>
      #        auth_mech: :mongodb_cr

      development:
        clients:
          default:
            uri: mongodb+srv://admin:admin123@test.guzqdnv.mongodb.net/test
            options:
              server_selection_timeout: 5

      test:
        clients:
          default:
            database: kd1k_test
            hosts:
              - localhost:27017
            options:
              server_selection_timeout: 5

      production:
        clients:
          default:
            uri: <%= ENV['MONGODB_URI'] %>
            options:
              server_selection_timeout: 5


